a=input('Enter A Number: ')
b=input('Now Enter Another Number: ')
c=input('Now Enter One Simbol: ')
sum=a+b
print('\nData Type sum :',sum,type(sum))
sum=((a+b)+c)
print('\nData Type sum :',sum,type(sum))
sum=a+c
print('\nData Type sum :',sum,type(sum))
sum=int(a)+int(b)
print('\nData Type sum :',sum,type(sum))
sum = int(a) + int(b) + ord(c)
print('\nData Type sum :',sum,type(sum))
sum = int(a) + int(b) * ord(c)
print('\nData Type sum :',sum,type(sum))
sum = int(a) + int(b) % ord(c)
print('\nData Type sum :',sum,type(sum))
sum = int(a) + int(b) / ord(c)
print('\nData Type sum :',sum,type(sum))
sum=float(sum)
print('\nData Type sum :',sum,type(sum))
sum=chr(int(sum))
#sum=chr(sum)
print('\nData Type sum :',sum,type(sum))
sumh=hex(ord(sum))
print('\nData Type sum :',sumh,type(sumh))
sumo=oct(ord(sum))
print('\nData Type sum :',sumo,type(sumo))
suma=ascii(ord(sum))
print('\nData Type sum :',suma,type(suma))
sumh=hash(ord(sum))
print('\nData Type sum :',sumh,type(sumh))

